print_info() {
    echo
    info title
    info underline
    info "OS" distro
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "DE" de
    info "Terminal" term
    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory
}

image_backend="ascii"
image_source="$HOME/.config/neofetch/reyos-ascii.txt"
ascii_colors=(3 7)
colors=(7 7 7 7 7 7)
ascii_bold="on"
bold="on"
underline_enabled="on"
separator=" →"
memory_percent="on"
memory_unit="gib"
