# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# unpackfs copies the live-only autologin and Calamares sudo permission into the installed target.
# Remove both before the new user session is created and SDDM is enabled.
dontChroot: true
timeout: 30
script:
    - "rm -f ${ROOT}/etc/sddm.conf.d/autologin.conf ${ROOT}/etc/sudoers.d/49-reyos-live-calamares ${ROOT}/usr/share/applications/reyos-installer.desktop"
